services:
  telegram-bot-api:
    build: 
      context: telegram-bot-api
      args:
        - BUILD_CPU_COUNT=${BUILD_CPU_COUNT}
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_LOCAL=true
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    restart: always
  goodsecretarybot:
    build:
      context: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_BOT_API_URL=${TELEGRAM_BOT_API_URL}
      - SENTRY_DSN=${SENTRY_DSN}
      - TRANSCRIPTION_ENGINE=${TRANSCRIPTION_ENGINE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - BOT_USERNAME=${BOT_USERNAME}
      - SUPPORT_USERNAME=${SUPPORT_USERNAME}
      - AVAILABLE_MINUTES=${AVAILABLE_MINUTES}
      - LEFT_WARNING_MINUTES=${LEFT_WARNING_MINUTES}
      - CURRENCY_RATE=${CURRENCY_RATE}
      - ALLOWED_CHAT_IDS=${ALLOWED_CHAT_IDS}
    restart: always
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
      - ./data:/app/data
    depends_on:
      - telegram-bot-api

volumes:
  telegram-bot-api-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=500m,uid=1000"
