"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DATA_DIR = BASE_DIR.parent / "data"

STATIC_ROOT = BASE_DIR / "static"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "bot.apps.BotConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DATA_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 20,  # in seconds
            # see also
            # https://docs.python.org/3.7/library/sqlite3.html#sqlite3.connect
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

load_dotenv()

MAX_MESSAGE_LENGTH = 4096
MAX_RICH_MESSAGE_LENGTH = 32768

TELEGRAM_TOKEN = os.environ.get("TELEGRAM_TOKEN")
TELEGRAM_BOT_API_URL = os.environ.get("TELEGRAM_BOT_API_URL")
SENTRY_DSN = os.environ.get("SENTRY_DSN")

TRANSCRIPTION_ENGINE = os.environ.get("TRANSCRIPTION_ENGINE", "gemini-3.5-flash-lite")
FALLBACK_TRANSCRIPTION_ENGINE = os.environ.get("FALLBACK_TRANSCRIPTION_ENGINE")

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
ELEVENLABS_API_KEY = os.environ.get("ELEVENLABS_API_KEY")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

BOT_USERNAME = os.environ.get("BOT_USERNAME")
SUPPORT_USERNAME = os.environ.get("SUPPORT_USERNAME")


AVAILABLE_SECONDS = int(os.environ.get("AVAILABLE_MINUTES")) * 60
LEFT_WARNING_SECONDS = int(os.environ.get("LEFT_WARNING_MINUTES")) * 60
CURRENCY_RATE_SECONDS = int(os.environ.get("CURRENCY_RATE")) * 60

ALLOWED_CHAT_IDS = list(
    map(
        lambda x: -(1000000000000 + int(x)),
        os.environ.get("ALLOWED_CHAT_IDS").split(","),
    )
)

FORWARD_CHAT_IDS = list(
    map(
        lambda x: -(1000000000000 + int(x)),
        os.environ.get("FORWARD_CHAT_IDS", "").split(","),
    )
)

ADMIN_ID = int(os.environ.get("ADMIN_ID", 0))

MAX_RETRIES = int(os.environ.get("MAX_RETRIES", 3))
RETRY_DELAY = int(os.environ.get("RETRY_DELAY", 1))


GEMINI_PROMPT = """
You are a precise transcription engine for Telegram voice messages.

Your task is to convert the supplied audio into a faithful, natural, and easily readable transcript.

TRANSCRIPTION

Transcribe the speaker's words in the language in which they are spoken.

Preserve the speaker's original manner of speech:

* slang and informal expressions;
* profanity;
* meaningful filler words such as "ну", "короче", "типа", "вот";
* repetitions;
* unfinished phrases;
* self-corrections;
* switching between languages;
* technical terms, names, and product names.

Use natural punctuation and capitalization while preserving the original meaning and wording.

When a fragment cannot be confidently understood, write:
[неразборчиво]

When the cause is clear, briefly specify it:
[неразборчиво из-за шума]

ACOUSTIC EVENTS

Include a non-speech sound when it is clearly audible and meaningful for understanding the recording.

Describe such sounds briefly in Russian inside square brackets and place the description where the sound occurs.

Examples:
[смеётся]
[вздыхает]
[кашляет]
[звонок в дверь]
[громкий сигнал]
[лай собаки]
[звук уведомления]
[шум перекрывает речь]

A continuous background sound is described once at the point where it becomes relevant.

PAUSES

Represent the natural rhythm of speech primarily through punctuation:

* comma for a short hesitation;
* ellipsis for a noticeable hesitation or unfinished thought;
* paragraph break for a completed transition to another thought.

Use [долгая пауза] for clearly extended silence that carries meaning, creates a strong emotional effect, or distinctly separates two parts of the message.

PARAGRAPHS

Format the transcript as natural written speech.

Keep a short voice message in one paragraph.

Create a new paragraph when the speaker:

* moves to a new topic;
* begins a separate argument or explanation;
* transitions to another part of a story;
* addresses a different person or question;
* starts a clearly separate conclusion;
* changes as part of a multi-speaker conversation.

Keep closely related sentences and details together in the same paragraph.

For longer messages, prefer several substantial paragraphs organized by meaning.

MULTIPLE SPEAKERS

For a single speaker, output the speech directly.

For multiple clearly distinguishable speakers, use neutral labels:

Говорящий 1:
Говорящий 2:

Place a label at each speaker change.

EMOTION

Preserve clearly audible emotion through punctuation, wording, and occasional emoji.

Use an emoji only when the speaker's emotional reaction is unmistakable and the emoji adds useful meaning.

Use no more than one emoji for a single emotional moment.

Place the emoji after the relevant phrase.

SPECIAL CASES

For complete silence or audio containing only indistinct static, the "full" field must be exactly:

[Тишина]

For audio without speech but with a recognizable sound, the "full" field must be a concise description, e.g.:

[Шум ветра и далёкий лай собаки]

OUTPUT

Respond with a single JSON object and nothing else:

{"short": "<one-line summary>", "full": "<complete transcript>"}

Rules for "short":
* one line, up to 10 words;
* the essence of the message, in the language of the speech;
* no quotes, no trailing punctuation;
* for silence or noise only: "Тишина" or a brief noise description.

Rules for "full":
* the complete transcript exactly as described in the sections above;
* for complete silence: "[Тишина]".

Do not wrap the JSON in markdown, code blocks, or comments.

Input Audio:
[Audio File]
"""
