defmodule TelegramVoiceTranscriberAsh.Repo.Migrations.AddMeteringLedger do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:transcription_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :audio_duration, :bigint, null: false
      add :duration_ms, :bigint
      add :status, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :subscriber_id, :uuid, null: false
    end

    create table(:subscribers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:transcription_logs) do
      modify :subscriber_id,
             references(:subscribers,
               column: :id,
               name: "transcription_logs_subscriber_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:subscribers) do
      add :hashed_user_id, :text, null: false
      add :left_free_seconds, :bigint, null: false
      add :left_purchased_seconds, :bigint, null: false, default: 0

      add :last_free_reset_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :warned_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:subscribers, [:hashed_user_id],
             name: "subscribers_unique_hashed_user_id_index"
           )

    create constraint(:subscribers, :left_free_seconds_non_negative,
             check: """
               left_free_seconds >= 0
             """
           )

    create constraint(:subscribers, :left_purchased_seconds_non_negative,
             check: """
               left_purchased_seconds >= 0
             """
           )
  end

  def down do
    drop_if_exists constraint(:subscribers, :left_purchased_seconds_non_negative)

    drop_if_exists constraint(:subscribers, :left_free_seconds_non_negative)

    drop_if_exists unique_index(:subscribers, [:hashed_user_id],
                     name: "subscribers_unique_hashed_user_id_index"
                   )

    alter table(:subscribers) do
      remove :updated_at
      remove :created_at
      remove :warned_at
      remove :last_free_reset_at
      remove :left_purchased_seconds
      remove :left_free_seconds
      remove :hashed_user_id
    end

    drop constraint(:transcription_logs, "transcription_logs_subscriber_id_fkey")

    alter table(:transcription_logs) do
      modify :subscriber_id, :uuid
    end

    drop table(:subscribers)

    drop table(:transcription_logs)
  end
end
