defmodule TelegramVoiceTranscriberAsh.Repo.Migrations.AddStarsPayments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:payments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :charge_id, :text, null: false
      add :stars, :bigint, null: false
      add :seconds_credited, :bigint, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :subscriber_id,
          references(:subscribers,
            column: :id,
            name: "payments_subscriber_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:payments, [:charge_id], name: "payments_unique_charge_id_index")
  end

  def down do
    drop constraint(:payments, "payments_subscriber_id_fkey")

    drop_if_exists unique_index(:payments, [:charge_id], name: "payments_unique_charge_id_index")

    drop table(:payments)
  end
end
